/**
 * Tests for the Spotify playlist exporter.
 * All network calls (fetch) and native modules are mocked.
 */
import { spotifyExporter } from '../../services/export/spotify';

// ─── Mock expo-secure-store ───────────────────────────────────────────────────
const secureStore: Record<string, string> = {};
jest.mock('expo-secure-store', () => ({
  setItemAsync: jest.fn(async (key: string, value: string) => { secureStore[key] = value; }),
  getItemAsync: jest.fn(async (key: string) => secureStore[key] ?? null),
  deleteItemAsync: jest.fn(async (key: string) => { delete secureStore[key]; }),
}));

// ─── Mock expo-web-browser ────────────────────────────────────────────────────
jest.mock('expo-web-browser', () => ({
  maybeCompleteAuthSession: jest.fn(),
  openAuthSessionAsync: jest.fn(),
}));
import * as WebBrowser from 'expo-web-browser';
const mockOpenAuth = WebBrowser.openAuthSessionAsync as jest.Mock;

// ─── Mock expo-crypto ─────────────────────────────────────────────────────────
jest.mock('expo-crypto', () => ({
  getRandomBytesAsync: jest.fn(async () => new Uint8Array(32).fill(1)),
  digestStringAsync: jest.fn(async () => 'dGVzdA=='), // base64 for "test"
  CryptoDigestAlgorithm: { SHA256: 'SHA-256' },
  CryptoEncoding: { BASE64: 'base64' },
}));

// ─── Mock export config ───────────────────────────────────────────────────────
jest.mock('../../services/export/config', () => ({
  exportConfig: { spotifyClientId: 'test-client-id' },
}));

// ─── Mock global fetch ────────────────────────────────────────────────────────
const mockFetch = jest.fn();
global.fetch = mockFetch;

beforeEach(() => {
  Object.keys(secureStore).forEach((k) => delete secureStore[k]);
  mockFetch.mockReset();
  mockOpenAuth.mockReset();
});

// ─── isAuthenticated ──────────────────────────────────────────────────────────

describe('spotifyExporter.isAuthenticated', () => {
  it('returns false when no token is stored', async () => {
    expect(await spotifyExporter.isAuthenticated()).toBe(false);
  });

  it('returns true when a valid token exists', async () => {
    secureStore['export_spotify_token'] = JSON.stringify({
      accessToken: 'tok',
      expiresAt: Date.now() + 3600_000,
    });
    expect(await spotifyExporter.isAuthenticated()).toBe(true);
  });

  it('returns false when the stored token is expired', async () => {
    secureStore['export_spotify_token'] = JSON.stringify({
      accessToken: 'tok',
      expiresAt: Date.now() - 1,
    });
    expect(await spotifyExporter.isAuthenticated()).toBe(false);
  });
});

// ─── authenticate ─────────────────────────────────────────────────────────────

describe('spotifyExporter.authenticate', () => {
  it('throws when spotifyClientId is not configured', async () => {
    const { exportConfig } = jest.requireMock('../../services/export/config') as {
      exportConfig: { spotifyClientId: string };
    };
    const orig = exportConfig.spotifyClientId;
    exportConfig.spotifyClientId = '';
    await expect(spotifyExporter.authenticate()).rejects.toThrow(
      /EXPO_PUBLIC_SPOTIFY_CLIENT_ID/,
    );
    exportConfig.spotifyClientId = orig;
  });

  it('throws when the user cancels the OAuth flow', async () => {
    mockOpenAuth.mockResolvedValueOnce({ type: 'cancel' });
    await expect(spotifyExporter.authenticate()).rejects.toThrow(/annulée/);
  });

  it('throws on CSRF state mismatch', async () => {
    mockOpenAuth.mockResolvedValueOnce({
      type: 'success',
      url: 'chorus://oauth/spotify?code=abc&state=wrongstate',
    });
    await expect(spotifyExporter.authenticate()).rejects.toThrow(/CSRF/);
  });

  it('persists the access token on success', async () => {
    // The state is generated by base.ts — we capture it by spying on the URL.
    let capturedState = '';
    mockOpenAuth.mockImplementation(async (url: string) => {
      capturedState = new URL(url).searchParams.get('state') ?? '';
      return {
        type: 'success',
        url: `chorus://oauth/spotify?code=authcode123&state=${capturedState}`,
      };
    });
    mockFetch.mockResolvedValueOnce({
      ok: true,
      json: async () => ({
        access_token: 'sp_access',
        refresh_token: 'sp_refresh',
        expires_in: 3600,
      }),
    });

    await spotifyExporter.authenticate();
    const stored = JSON.parse(secureStore['export_spotify_token'] ?? 'null');
    expect(stored.accessToken).toBe('sp_access');
    expect(stored.refreshToken).toBe('sp_refresh');
  });

  it('throws when the token exchange fails', async () => {
    let capturedState = '';
    mockOpenAuth.mockImplementation(async (url: string) => {
      capturedState = new URL(url).searchParams.get('state') ?? '';
      return {
        type: 'success',
        url: `chorus://oauth/spotify?code=authcode123&state=${capturedState}`,
      };
    });
    mockFetch.mockResolvedValueOnce({ ok: false, text: async () => 'invalid_grant' });

    await expect(spotifyExporter.authenticate()).rejects.toThrow(/token Spotify/i);
  });
});

// ─── createPlaylist ───────────────────────────────────────────────────────────

describe('spotifyExporter.createPlaylist', () => {
  beforeEach(() => {
    secureStore['export_spotify_token'] = JSON.stringify({
      accessToken: 'valid_token',
      expiresAt: Date.now() + 3600_000,
    });
  });

  it('returns the playlist id on success', async () => {
    mockFetch
      .mockResolvedValueOnce({ ok: true, json: async () => ({ id: 'me123' }) })   // GET /me
      .mockResolvedValueOnce({ ok: true, json: async () => ({ id: 'pl456' }) });  // POST /playlists

    const id = await spotifyExporter.createPlaylist('Road Trip', 'fun playlist');
    expect(id).toBe('pl456');
    expect(mockFetch).toHaveBeenCalledTimes(2);
  });

  it('throws when not authenticated', async () => {
    delete secureStore['export_spotify_token'];
    await expect(spotifyExporter.createPlaylist('test')).rejects.toThrow(/Non authentifié/);
  });

  it('clears the token and throws on 401', async () => {
    mockFetch.mockResolvedValueOnce({ ok: false, status: 401, json: async () => ({}) });
    await expect(spotifyExporter.createPlaylist('test')).rejects.toThrow(/profil Spotify/);
    expect(secureStore['export_spotify_token']).toBeUndefined();
  });
});

// ─── addTracks ────────────────────────────────────────────────────────────────

describe('spotifyExporter.addTracks', () => {
  beforeEach(() => {
    secureStore['export_spotify_token'] = JSON.stringify({
      accessToken: 'valid_token',
      expiresAt: Date.now() + 3600_000,
    });
  });

  it('does nothing for an empty list', async () => {
    await spotifyExporter.addTracks('pl1', []);
    expect(mockFetch).not.toHaveBeenCalled();
  });

  it('converts open.spotify.com URLs to Spotify URIs', async () => {
    mockFetch.mockResolvedValueOnce({ ok: true, json: async () => ({}) });

    await spotifyExporter.addTracks('pl1', [
      'https://open.spotify.com/track/4iV5W9uYEdYUVa79Axb7Rh',
    ]);

    const body = JSON.parse(mockFetch.mock.calls[0][1].body as string);
    expect(body.uris).toEqual(['spotify:track:4iV5W9uYEdYUVa79Axb7Rh']);
  });

  it('calls onProgress after each batch', async () => {
    const urls = Array.from(
      { length: 5 },
      (_, i) => `https://open.spotify.com/track/track${i}`,
    );
    mockFetch.mockResolvedValue({ ok: true, json: async () => ({}) });

    const onProgress = jest.fn();
    await spotifyExporter.addTracks('pl1', urls, onProgress);
    expect(onProgress).toHaveBeenCalledWith(5, 5);
  });

  it('skips malformed URLs silently', async () => {
    mockFetch.mockResolvedValueOnce({ ok: true, json: async () => ({}) });
    // Mix of valid and invalid URLs
    await spotifyExporter.addTracks('pl1', [
      'https://open.spotify.com/track/abc123',
      'not-a-url',
      'https://open.spotify.com/track/def456',
    ]);
    const body = JSON.parse(mockFetch.mock.calls[0][1].body as string);
    expect(body.uris).toEqual(['spotify:track:abc123', 'spotify:track:def456']);
  });
});

// ─── getPlaylistUrl ───────────────────────────────────────────────────────────

describe('spotifyExporter.getPlaylistUrl', () => {
  it('returns the correct open.spotify.com URL', () => {
    expect(spotifyExporter.getPlaylistUrl('pl123')).toBe(
      'https://open.spotify.com/playlist/pl123',
    );
  });
});
